apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmiguelito/tools-deps.git
    targetRevision: main
    path: charts/postgresql
    helm:
      parameters:
        - name: image.repository
          value: postgres
        - name: image.tag
          value: "15"
  destination:
    server: https://kubernetes.default.svc
    namespace: default